README.md
=> fix(): grammar and things

lib/potassium/templates/application/recipes/asks/lang.rb, lib/potassium/templates/application/recipes/devise.rb, lib/potassium/templates/application/recipes/i18n.rb, lib/potassium/templates/application/template.rb
We added two languages for now, English and Spanish. We modify the default_locale setting accordingly. We have also added devise-i18n as a default. Thanks to @juliogarciag for his help.
=> feat(asks):add a question for choosing application language

potassium.gemspec
=> fix(): Add runtime dependencies

.editorconfig, lib/potassium/templates/application/assets/api/api_error_concern.rb, lib/potassium/templates/application/assets/api/base_controller.rb, lib/potassium/templates/application/assets/api/responder.rb, lib/potassium/templates/application/recipes/api.rb, lib/potassium/templates/application/recipes/asks/api.rb, lib/potassium/templates/application/template.rb
https://trello.com/c/T4lmd4zz/107-template-rails-en-modo-api
=> Api support

lib/potassium/templates/application/recipes/rbenv.rb
@blackjid I set it up to version `2.2.2`
=> feat(): Update ruby version

README.md, lib/potassium/cli/commands/create.rb, lib/potassium/newest_version_ensurer.rb, lib/potassium/text_spinner.rb, potassium.gemspec
=> Version Check

lib/potassium/templates/application/recipes/testing.rb
This is to be able to debug problems when sending emails
=> feat(): Change raise mail exceptions to true

CHANGELOG.md, README.md, lib/potassium/templates/application/assets/.buildpacks
fixes #37
this would help to perform tasks like db:migrate or db:seeds after a new version of the application is deployed
=> Adds a deploy-tasks buildpack

.ruby_style.yml, lib/potassium/cli/commands/create.rb, lib/potassium/cli/commands/install.rb, lib/potassium/templates/application/generator.rb, lib/potassium/templates/application/helpers/answer-helpers.rb, lib/potassium/templates/application/helpers/template-dsl.rb, lib/potassium/templates/application/recipes/asks/admin.rb, lib/potassium/templates/application/recipes/asks/api.rb, lib/potassium/templates/application/recipes/asks/database.rb, lib/potassium/templates/application/recipes/asks/devise.rb, lib/potassium/templates/application/recipes/asks/heroku.rb, lib/potassium/templates/application/recipes/asks/i18n.rb, lib/potassium/templates/application/recipes/asks/paperclip.rb, lib/potassium/templates/application/recipes/asks/pundit.rb, lib/potassium/templates/application/recipes/testing.rb, lib/potassium/text_spinner.rb
=> CLI Answers

README.md, lib/potassium/assets/.hound.yml, lib/potassium/assets/.rubocop.yml, lib/potassium/assets/README.md.erb, lib/potassium/recipes/style.rb, lib/potassium/templates/application.rb, spec/features/new_project_spec.rb
this is done via rubocop and hound
close #31 and #50
=> adds configuration for style guides

lib/potassium/assets/README.md.erb, lib/potassium/assets/bin/setup.erb, lib/potassium/cli/commands/install.rb, lib/potassium/helpers/answer-helpers.rb, lib/potassium/helpers/template-helpers.rb, lib/potassium/recipes/heroku.rb, lib/potassium/recipes/script.rb, lib/potassium/templates/application.rb, lib/potassium/templates/recipe.rb
- Creates the production and staging apps in heroku
- Creates the pipeline and adds the app to the pipeline
- Prepares de `bin/setup` script to access the app
close #33
=> adds heroku services support

lib/potassium/recipes/heroku.rb, spec/features/heroku_spec.rb
It should run db:migrate after deploy
closes #62
=> set the deploy tasks

README.md, docs/CONTRIBUTING.md, docs/DSL.md
=> updates the readme

README.md, docs/DSL.md, lib/potassium/helpers/template-helpers.rb, lib/potassium/recipes/admin.rb, lib/potassium/recipes/angular_admin.rb, lib/potassium/recipes/api.rb, lib/potassium/recipes/delayed_job.rb, lib/potassium/recipes/devise.rb, lib/potassium/recipes/heroku.rb, lib/potassium/recipes/paperclip.rb, lib/potassium/recipes/pundit.rb, lib/potassium/recipes/script.rb
Also adds support to force the recipe installation, this will be useful when migrating older projects
=> improve the what recipes define if they are installed

lib/potassium/recipes/database.rb, spec/features/new_project_spec.rb, spec/support/potassium_test_helpers.rb
postgres should go first as it should be our default option to run applicacions, specially on heroku
=> use postgresql by default

lib/potassium/assets/lib/tasks/auto_annotate_models.rake, lib/potassium/recipes/annotate.rb, lib/potassium/templates/application.rb
@blackjid, not sure about what to put in specs for this.
=> feat(): adds annotate recipe

lib/potassium/assets/testing/rails_helper.rb
=> Fix shoulda matchers

spec/features/heroku_spec.rb
=> fix(specs.Heroku): replace fit method with it

CHANGELOG.md, lib/potassium/version.rb
- Use `rails 5.1.1`
- Bump potassium version to 5.1.1
=> Update to rails 5.1.1

CHANGELOG.md, lib/potassium/recipes/database.rb
=> fix(recipes/database): enforce pg gem version

lib/potassium/assets/config/database_mysql.yml.erb, lib/potassium/assets/config/database_postgresql.yml.erb
Reverts platanus/potassium#174
=> Revert "fix(config): remove production database url default value"

lib/potassium/recipes/listen.rb, lib/potassium/templates/application.rb
=> fix(): add required gem listen to development group in gemfile

lib/potassium/recipes/puma.rb
=> fix(rack): remove legacy setter for timeout in favor of env vars

lib/potassium/recipes/database.rb
=> chore(databases): remove explicit version for pg gem

lib/potassium/version.rb
Updates version of ruby (pins to minor instead of patch giving more freedom to use local versions) and rubocop to current platanus version
=> Version tuning

.editorconfig, lib/potassium/assets/Makefile.erb, lib/potassium/assets/README.yml, lib/potassium/assets/bin/setup.erb, lib/potassium/assets/config/database_mysql.yml.erb, lib/potassium/assets/config/database_postgresql.yml.erb, lib/potassium/assets/docker-compose.yml, lib/potassium/helpers/docker-helpers.rb, lib/potassium/recipes/ci.rb, lib/potassium/recipes/database_container.rb, lib/potassium/templates/application.rb, lib/potassium/version.rb, spec/features/database_container_spec.rb
This PR adds dockerized database services for development
- Modifies `DockerHelpers` to manipulate leafs of given root sections of `docker-compose` files
- Adds the `database_container` recipe, which populates `docker-compose.yml`, `Makefile`, `config/database.yml` and `bin/setup` files to develop using a containerized database
- Updates README with new dependencies (and deprecates `boxen`!)
- Pins `postgres` and `mysql` versions in `version.rb` file to standarize docker images between development and CI environments.
Finally! 🚀
=> Database container

README.md, lib/potassium/assets/.buildpacks, lib/potassium/assets/Procfile, lib/potassium/assets/bin/release, lib/potassium/recipes/heroku.rb, spec/features/heroku_spec.rb
=> feat(heroku): implement release phase

lib/potassium/cli_options.rb
=> fix(storage): reinstate file storage question

.circleci/config.yml, spec/features/new_project_spec.rb
=> fix(circleci): use ruby image instead of old ubuntu one

lib/potassium/assets/sidekiq_scheduler.yml
=> fix(scheduler): comment out schedule entry in yml

lib/potassium/recipes/api.rb
=> feat(api): add raven capture in error handler if sentry enabled

lib/potassium/assets/docker-compose.ci.yml, lib/potassium/recipes/ci.rb
=> fix(ci): include test_data volume for bundler related data

lib/potassium/recipes/file_storage.rb
=> fix(storage): support None passed as cli flag option

CHANGELOG.md, lib/potassium/recipes/mailer.rb
=> fix(mailer): avoid sidekiq repeated installation

CHANGELOG.md, lib/potassium/assets/Makefile.erb, lib/potassium/assets/config/database_mysql.yml.erb, lib/potassium/assets/config/database_postgresql.yml.erb
=> feat(compose): dasherize app name for docker consistency

CHANGELOG.md, lib/potassium/assets/.circleci/config.yml.erb, lib/potassium/assets/app/javascript/app.spec.js, lib/potassium/assets/bin/cibuild.erb, lib/potassium/assets/docker-compose.ci.yml, lib/potassium/recipes/ci.rb, lib/potassium/recipes/front_end.rb
- Agrega jest, sus dependencias, y un ejemplo de archivo `.spec`
- Agrega lo necesario para que corra los tests en circleci
=> Add vue tests

lib/potassium/recipes/vue_admin.rb
=> fix(vue-admin): only set frontend to vue if selected

CHANGELOG.md, lib/potassium/recipes/database.rb
=> Fix strong migrations installation

CHANGELOG.md, README.md, lib/potassium/cli_options.rb, lib/potassium/recipes/github.rb, spec/features/github_spec.rb
This PR allows the user to select their user or organization when automatically creating the Github repository.
Closes #317
=> Custom GitHub

CHANGELOG.md
Fix new feature placement in changelog
=> docs(changelog): fix custom Github changelog placement

CHANGELOG.md, lib/potassium/assets/.github/pull_request_template.md, lib/potassium/recipes/github.rb, spec/features/github_spec.rb
Adds PR template if github option is selected
=> feat(github): add pull request template

CHANGELOG.md, README.md, lib/potassium/assets/app/views/shared/_gtm_body.html.erb, lib/potassium/assets/app/views/shared/_gtm_head.html.erb, lib/potassium/cli_options.rb, lib/potassium/recipes/google_tag_manager.rb, lib/potassium/templates/application.rb, spec/features/google_tag_manager_spec.rb
Create a recipe for #104 
This PR adds google tag manager as a recipe.
=> feat(): add gtm recipe

.rubocop.yml, CHANGELOG.md, lib/potassium/assets/sidekiq_scheduler.yml, lib/potassium/recipes/background_processor.rb, lib/potassium/recipes/mailer.rb, lib/potassium/recipes/schedule.rb, spec/features/background_processor_spec.rb, spec/features/mailer_spec.rb, spec/features/schedule_spec.rb
For mails to work with sidekiq, a `mailers` queue must be defined. This PR adds that queue to `sidekiq.yml` when running `create` or `install`. This was done by adding in bg_processor a new public method, `add_mailer_queue`. This is used in `add_sidekiq` and in the mailer recipe when sidekiq is already installed at the moment of running the mailer install.
Other things in this PR:
- Moves add_sidekiq away from `private`, as it wasn't accesible from mailer recipe
- In bg_processor recipe, checks for `None` value in mailer recipe. This is the default test value, and as it was before it was wrongfully enabling the first recipe for all tests
- In schedule recipe, appends schedule section to `.yml`, in order to not remove `mailers` queue (and any additional content it may have)
- Disables …
=> Mailer queue

CHANGELOG.md, lib/potassium/assets/.circleci/config.yml.erb
=> feat(ci): explicitly install node from .node-version file in ci build

CHANGELOG.md, README.md, lib/potassium/recipes/monitoring.rb, lib/potassium/templates/application.rb
=> feat(recipe): add monitoring recipe with scout gem

CHANGELOG.md, lib/potassium/recipes/file_storage.rb
=> fix(file-storage): update shrines analyzer marcel w/o mimemagic dep

CHANGELOG.md, lib/potassium/recipes/admin.rb
=> feat(active-admin): update AA to 2.9

lib/potassium/cli_options.rb, lib/potassium/recipes/rails.rb, lib/potassium/recipes/spring.rb, lib/potassium/templates/application.rb, spec/support/potassium_test_helpers.rb
Tests freeze when run locally due to the spring gem.
I made the installation optional to disable it in the test environment.
I didn't add tests because like I said they freeze locally.
=> Spring bug

CHANGELOG.md, lib/potassium/assets/.circleci/config.yml.erb, lib/potassium/assets/testing/simplecov_config.rb, lib/potassium/recipes/coverage.rb, lib/potassium/templates/application.rb, spec/features/coverage_spec.rb
- Configure SimpleCov gem
- Configure VSCode linter: https://github.com/platanus/simplecov_linter_formatter
- Configure CI to run SimpleCov on GH PRs using reviewdog: https://github.com/platanus/simplecov_text_formatter
=> Configure SimpleCov gem

lib/potassium/assets/.circleci/config.yml.erb, lib/potassium/assets/README.yml, lib/potassium/assets/testing/.rspec, lib/potassium/assets/testing/devise_config.rb, lib/potassium/assets/testing/factory_bot_config.rb, lib/potassium/assets/testing/faker_config.rb, lib/potassium/assets/testing/power_types_config.rb, lib/potassium/assets/testing/rails_helper.rb, lib/potassium/assets/testing/shoulda_matchers_config.rb, lib/potassium/assets/testing/simplecov_config.rb, lib/potassium/assets/testing/system_tests_config.rb, lib/potassium/recipes/coverage.rb, lib/potassium/recipes/testing.rb, spec/features/coverage_spec.rb, spec/features/testing_spec.rb
- Add tests to testing recipe.
- Configure system tests.
- Add useful info to autogenerated README and rails_helper.rb
=> System specs

CHANGELOG.md, lib/potassium/version.rb
Bumps rails to latest 6 version
=> chore(): bump rails to latest patch

lib/potassium/assets/.circleci/config.yml.erb
Fixes CircleCI not finding a variable.
=> fix(circleci): make env variable explicit

lib/potassium/recipes/admin.rb
Adds miscellaneous fixes for arctic_skin:
* Adds scroll to the sidebar to avoid filters disappearing if there are too many.
* Adds a z-index to the calendar to make it appear above the next filter instead of hidden under it.
* Reverses the date range input since it's backwards by default.
=> fix(admin): fix css issues

lib/potassium/assets/.eslintrc.json, lib/potassium/recipes/style.rb
Se agrega [eslint-plugin-platanus](https://github.com/platanus/eslint-plugin-platanus) y su config recomendada
=> feat(style): add eslint-plugin-platanus

lib/potassium/assets/app/javascript/api/index.ts, lib/potassium/assets/tsconfig.json, lib/potassium/recipes/front_end.rb
- Arregla problema causado por los tests de jest siendo compilados en heroku
- Agrega types de humps
=> typescript fixes

lib/potassium/assets/app/javascript/api/index.ts, lib/potassium/assets/tsconfig.json, lib/potassium/recipes/front_end.rb
- Arregla problema causado por los tests de jest siendo compilados en heroku
- Agrega types de humps
- Agrega export faltante a archivo
=> Fix typescript issues

CHANGELOG.md, lib/potassium/version.rb
Adds missing changelog entries and updates version
=> Release 7.1.0

lib/potassium/assets/README.yml
=> fix(): heroku dashboard typo

CHANGELOG.md, lib/potassium/assets/.circleci/config.yml.erb, lib/potassium/recipes/ci.rb, spec/features/ci_spec.rb
Use repo analyzer from [Platanus docker image](https://hub.docker.com/r/platanus/repo-analyzer)
=> Docker Repo Analyzer
