- lib/potassium/templates/application/recipes/admin.rb
- lib/potassium/templates/application/recipes/asks/admin.rb
I think it's safe to say we should use activeadmin_addons if we use activeadmin at all
> feat(ActiveAdmin): Add ActiveAdminAddon gem to admin recipe

- lib/potassium/templates/application/assets/.rbenv-vars.example
The name of the created database was not the same
saved on the `.rbenv-vars`
[Closes #9]
> fix(rbenv-vars): Fix database name

- CHANGELOG.md
- lib/potassium/templates/application/recipes/rbenv.rb
The idea is to have a endpoint to get the latests ruby version that we
are using at platanus. The endpoint is http://ruby.platan.us/latest
Potassium get the version the the service and generates the
corresponding `.ruby-version`
If the service is down, if fallback to whatever ruby version potassium
it's being run. This is done via the RBENV_VERSION environmental
variable.
> feat(rbenv): gets ruby version from service

- lib/potassium/templates/application/recipes/heroku.rb
> fix(heroku): Move logging gem to the correct groups

- CHANGELOG.md
- README.md
- circle.yml
- lib/potassium/templates/application/assets/Dockerfile.ci
- lib/potassium/templates/application/assets/README.md.erb
- lib/potassium/templates/application/assets/bin/cibuild.erb
- lib/potassium/templates/application/assets/circle.yml
- lib/potassium/templates/application/assets/config/database_mysql.yml.erb
- lib/potassium/templates/application/assets/config/database_postgresql.yml.erb
- lib/potassium/templates/application/assets/docker-compose.ci.yml
- lib/potassium/templates/application/helpers/docker-helpers.rb
- lib/potassium/templates/application/helpers/template-dsl.rb
- lib/potassium/templates/application/recipes/ci.rb
- lib/potassium/templates/application/template.rb
- spec/features/ci_spec.rb
- spec/support/potassium_test_helpers.rb
It adds
- docker configuration to run continuous integration
- circleci config
- improve testing helpers to enable project creation with different options
> Adds support for continuous integration

- .gitignore
- .rubocop.yml
- lib/potassium/version.rb
I was testing this over the refactor..
I think there is something wrong about the rubocop test. 
Rubocop should use the configuration files in the dummy project not the one on the root of potassium
those could easily diverge and be different. https://github.com/platanus/potassium/blob/remote_rubocop/spec/support/potassium_test_helpers.rb#L91
This also means that we need to complete the #31 issue
> Remote rubocop

- lib/potassium/assets/bin/setup.erb
- lib/potassium/assets/bin/setup_heroku.erb
- lib/potassium/recipes/heroku.rb
- spec/features/heroku_spec.rb
The setup script will run the heroku setup script. But now the user can run the heroku setup independently. This close the issue #71 by not having to run the setup script when the project already exists
> move the heroku setup outside the setup script, close #71

- lib/potassium/recipes/heroku.rb
- spec/support/fake_heroku.rb
the heroku pipelines are now a core part of the heroku cli, there is no need to add a plugin. We can assume the pipelines command will be there for us
> remote checking for heroku pipelines

- lib/potassium/assets/config/database_mysql.yml.erb
- lib/potassium/assets/config/database_postgresql.yml.erb
- lib/potassium/assets/config/environments/staging.rb
- lib/potassium/assets/config/secrets.yml.erb
- lib/potassium/recipes/cleanup.rb
- lib/potassium/recipes/heroku.rb
- lib/potassium/recipes/puma.rb
- lib/potassium/recipes/staging.rb
- lib/potassium/templates/application.rb
We should use production environment in staging servers, that way we encourage the staging-production parity, close #87
> remove staging environment

- lib/potassium/assets/config/puma.rb
- lib/potassium/assets/docker-compose.ci.yml
- lib/potassium/assets/testing/rails_helper.rb
- lib/potassium/recipes/heroku.rb
- lib/potassium/templates/application.rb
- spec/features/heroku_spec.rb
To avoid duplication, with should rely on RACK_ENV as Rails.env ask for RAILS_ENV and then fallback to RACK_ENV
> remove RAILS_ENV

- lib/potassium/recipes/tzinfo.rb
- lib/potassium/templates/application.rb
Adds `tzinfo-data` gem to help ActiveSupport resolve timezones consistently.
> Add tzinfo-data

- CHANGELOG.md
- lib/potassium/recipes/delayed_job.rb
- lib/potassium/recipes/mailer.rb
- Agregué `config.active_job.queue_adapter = :inline` a development
- Hice que si se se selecciona SES para enviar mails, en development se use letter_opener. En el caso de sendgrid no se puede porque al no tener los templates en rails, al cambiar el adapter a letter_opener, da este error: `ActionView::MissingTemplate: Missing`
> feat(mailer): config development environment

- CHANGELOG.md
- lib/potassium/recipes/better_errors.rb
- lib/potassium/recipes/quiet_assets.rb
- lib/potassium/templates/application.rb
- lib/potassium/version.rb
Estas gemas para desarrollo son muy cómodas. Quiet assets hace que la consola no escriba tanta cosa y better errors cambia la pantalla de error por una mas usable. Además binding of caller, entrega una pequeña consola para depurar estilo pry.
> chore(gems): quiet_assets and better_errors gems

- CHANGELOG.md
- lib/potassium/assets/config/mailer.rb.erb
- lib/potassium/recipes/heroku.rb
- lib/potassium/recipes/mailer.rb
Move heroku stage to production only and us it in the mailer recipe only if heroku is being used
> remove heroku dependency from mailer recipe

- lib/potassium/recipes/schedule.rb
This was failing because we were checking the existence of the sidekiq-scheduler gem using a string instead of a regex.
> fix(schedule): recipe check using regex

- lib/potassium/assets/config/database_mysql.yml.erb
- lib/potassium/assets/config/database_postgresql.yml.erb
La `url` de la base de datos de producción debe existir en el yml de la configuración. Es por lo anterior que dejar como _default_ un string vacío no es conveniente ya que en caso de que esta variable no sea ingresada, será difícil reconocer de dónde viene el problema. Este PR remueve el valor por defecto para que la aplicación lance una excepción en caso de que esta variable falte.
> fix(config): remove production database url default value

- lib/potassium/assets/config/puma.rb
This PR sets 1 day timeout for puma workers on development.
This enables long `binding.pry` debugs without losing all the context due to puma restarting the process.
👍
> fix(puma): set 1 day timeout for puma workers on development

- lib/potassium/assets/bin/cibuild.erb
- lib/potassium/recipes/ci.rb
After creating a new repo using `database_container` recipe, the CI env is broken because the `database.yml` file no longer uses `POSTGRESQL_*` env vars.
- Use `DB_*` env vars in `cibuild` and `docker-compose.ci.yml` files
> fix(ci): update database env vars with database_container vars

- lib/potassium/recipes/mailer.rb
- spec/features/mailer_spec.rb
- Fixes call to `ENV['SENDGRID_API']`, should've been `SENDGRID_API_KEY`
- Adds configuration to `development.rb` to use `sendgrid_dev` as delivery method whe user selects `sendgrid` as mailer
- Adds missing mailer tests
> Sendgrid dev

- lib/potassium/assets/bin/cibuild.erb
- spec/features/database_container_spec.rb
- spec/spec_helper.rb
- spec/support/potassium_test_helpers.rb
Cleanup docker environment after running tests
- Use new test helper to run `docker-compose down` after each test
- Remove command in after block database_container
- Remove one-off containers used in `cibuild`
Fixes #210
> Test env teardown

- potassium.gemspec
Because of the addition of `rubocop-rspec` to platanus linters in https://github.com/platanus/la-guia/pull/112 , the rubocop spec in potassium was broken.
This PR adds the needed dependency.
> fix(gemspec): add rubocop-rspec for compatibility with updated linters

- lib/potassium/assets/aws.rb
- lib/potassium/recipes/aws_sdk.rb
- lib/potassium/recipes/file_storage.rb
- lib/potassium/templates/application.rb
- spec/features/file_storage_spec.rb
- spec/features/new_project_spec.rb
This PR removes the gem `aws-sdk` in favor of the S3 specific one (`aws-sdk-s3`).
As reported in https://github.com/thoughtbot/paperclip/issues/2484 an initializer like the one in `assets/aws.rb` was necessary for the gem to work correctly, but since paperclip `6.0.0`, it is no longer needed because of the improvement introduced in https://github.com/thoughtbot/paperclip/pull/2481. In this PR the initializer is removed.
As adding the initializer was the only thing that the whole `aws_sdk` recipe was doing, besides adding the old gem, it is also removed in this PR.
> Remove unnecesary aws-sdk gems

- lib/potassium/recipes/database_container.rb
Call to `create` method was missing when installing the recipe `database_container`, resulting in missing necessary files to run a database container on legacy projects.
> fix(database-container): make install option work

- lib/potassium/recipes/front_end.rb
Arregla error en creación de proyecto nuevo. 
Se usa la última versión estable publicada en RubyGems en vez de confiar que el último commit de github es compatible con nuestro setup.
> fix(frontend): use webpacker from rubygems

- README.md
- lib/potassium/assets/bin/release
- lib/potassium/recipes/data_migrate.rb
- lib/potassium/templates/application.rb
- spec/features/data_migrate_spec.rb
- spec/features/heroku_spec.rb
- Adds new recipe to include gem [`data-migrate`](https://github.com/ilyakatz/data-migrate) in new projects
- Add configuration to `auto_annotate_models` task to generate annotations when using `data-migrate` rake commands (ending in `:with:data`). Configuration was taken from `annotate_models` source code, [here](https://github.com/ctran/annotate_models/blob/develop/lib/tasks/annotate_models_migrate.rake#L7)
- Run `db:migrate:with_data` in release phase
Closes #175
> Add data migrate

- lib/potassium/recipes/front_end.rb
- spec/features/front_end.rb
- Se hace que por defecto la aplicación obtenga Vue de la distribución que incluye el compilador. Esto permite usar vue como usualmente lo hacemos en platanus: componentes dentro de vistas/rutas rails, para agregar interactividad sin transformar toda la app en una SPA
- Se adapta el código del `application.js` a partir de lo que se genera con webpacker en [`hello_vue.vue`](https://github.com/rails/webpacker/blob/40987fed31a59dee9501f2832a9ee09603739175/lib/install/examples/vue/hello_vue.js#L35)
- Se incluye en el layout como primer hijo del body un div con id `vue-app` que funciona como el elemento donde se montará vue, permitiendo el uso de componentes en cualquier vista
- Se agrega el componente `app` que se genera como ejemplo también al layout, para que cuando se genere la primera …
> Vue in compiler mode

- lib/potassium/recipes/background_processor.rb
No estaba agregando la linea en el `Procfile` si `sidekiq` se instala después.
> fix(background_processor): add check for installed heroku recipe

- lib/potassium/helpers/gem-helpers.rb
> fix(gem-helpers): pass gem version to gather gem as a hash option

- lib/potassium/assets/Makefile.erb
Se agregan los comandos:
`backup-staging`
`backup-production`
`restore-from-staging`
`restore-from-production`
debido a que los comandos de parity no están funcionando post docker y no tiene sentido mantener parity por nuestro lado para esos comandos.
> feat(makefile): add restore-from commands for pg_restore

- .circleci/config.yml
This PR fixes the usage of cache in the ci build. Even though cache was saved and restored, paths weren't correctly assigned. 
That's because `bundle install` automatically saves dependencies under the default path defined via environment variables, in this case `/usr/local/bundle`. Changing it to `vendor/bundle` is the recommended way (`bundle install --path vendor/bundle`) but it breaks every test.
I also renamed cache keys/paths and added flags to bundle install to improve efficiency.
> fix(ci): correctly use cache for bundle dependencies

- CHANGELOG.md
- lib/potassium/recipes/admin.rb
This PR updates the admin recipe to use ActiveAdmin 2.6.0 version. It uses the `~> 2.6` notation so that we don't get _stuck_ in a minor (the last update from 1.1.0 to 1.3.0 was 2 years ago), and get updates until AA 3.0 version is released.  
Compatibility with ActiveAdmin Addons was tested by creating a new app with a sample model with many addons used for inputs and tables.
closes #245
> feat(active-admin): update active admin to 2.6

- .circleci/config.yml
- CHANGELOG.md
- potassium.gemspec
This PR updates bundler to `~> 2.0`. It also sorts alphabetically gemspec dependencies for consistency.
Some unknown bugs in the CI build were happening related to cache issues. For now cache restore will be disabled until I figure out the best way to deal with it.
closes #249
> Update bundler to 2.0

- CHANGELOG.md
- lib/potassium/recipes/admin.rb
- lib/potassium/recipes/draper.rb
- lib/potassium/version.rb
- spec/features/power_types_spec.rb
- spec/support/potassium_test_helpers.rb
This PR updates rails to 6.0.2.
In order to do that, `draper` needed to be updated to 3.1, alongside `active_skin`, which has many changes since the last published version (0.0.12) and they haven't made a release since 2015, so I referenced the github repo.
For rails 6.0.0 the behavior of rails generator's `generate` command changed slightly. Until 5.X every `generate sth` call was translated to a `bin/rails generate sth` command, but now it translates to `rails generate sth` ([rails/rails#34420](https://github.com/rails/rails/pull/34420/files#diff-5036eb99239f9418c0458f2a2ec4f496L226-L227)). As this change broke the test build in the CI, a new step is included in the spec helper to add `dummy_app/bin` to the `PATH` env var.
I slipped in a minor change in the power types specs, as they …
> Update rails to 6.0.2

- .circleci/config.yml
This PR reinstates cache for the ci build 🎉!
For caching the recommended way is to use the `vendor/bundle` path, but that brought some problems for this specific case, as some gems are used not in a `bundle exec` way, like when we use `potassium create` to create a project inside the specs. That meant that using that path would cause a not found error when requiring dependencies.
That's why I changed the env var `GEM_HOME` so that gems would be available outside of the scope of the root project. By doing that, as a nice side effect, gems for the spec created projects are also restored from cache.
Another major change is that cache is saved after specs are finished. This allows new project gems to be cached and not only potassium dependencies.
closes #256
> feat(ci): use cache and vendor/bundle as path

- CHANGELOG.md
- lib/potassium/cli/commands/create.rb
- lib/potassium/cli_options.rb
- lib/potassium/recipes/front_end.rb
This PR improves test speeds by changing default test values for some recipes to none. This prevents unnecesary steps like `rails generate active_storage:install` in every spec. 
This PR also adds 2 flags to the base template (which are passed to `rails new`): `--skip-bundle-install` and `--skip-webpack-install`. This addresses #252 as the frontend recipe is now the only one that executes `rails g webpack:install`. This also avoids multiple calls of `bundle install`, as it is called from one recipe.
**\* P.S.:** Webpacker gem is included by default by rails even with the `--skip-webpack-install` (and it is a expected behaviour, as the flag is only intended to skip the `:install` steps).
closes #252, closes #257
> Improve specs performance

- CHANGELOG.md
- lib/potassium/assets/lib/tasks/auto_annotate_models.rake
- lib/potassium/recipes/annotate.rb
Fixes #255:
- Problem occurred because of a breaking change in annotate v3
- Fixes gem's version to `~> 3.0` (latest release is 3.0.3)
> Fix annotate models

- .circleci/config.yml
- CHANGELOG.md
- potassium.gemspec
This PR improves CircleCI build time by considering timings for spec splitting. We gain more than one minute in total.
Further improvement is possible but I think that it should be done in a spec-by-spec basis, as some specs like the [ci recipe one](https://github.com/platanus/potassium/blob/master/spec/features/ci_spec.rb) are extremely slow.
> feat(ci): split specs by timings for parallel run

- CHANGELOG.md
- lib/potassium/assets/api/base_controller.rb
> fix(api): include error concern regardless of the environment

- CHANGELOG.md
- lib/potassium/recipes/rack_cors.rb
This PR updates rack-cors in order to remove vulnerability warnings from freshly bundled potassium projects. After this PR we should address #202. 
closes #265
> feat(rack-cors): update rack cors to ~> 1.1

- CHANGELOG.md
- lib/potassium/recipes/rack_cors.rb
This PR modifies the default configuration bundled by the rack-cors recipe. As of today we were allowing requests from any origin to any resource, which is a very unsafe configuration. The new config only allows get requests to the urls under `public` and index/show/create/update/delete requests for urls under `api`.
closes #202
> feat(cors): use safer api/public-only CORS configuration

- CHANGELOG.md
- lib/potassium/assets/Makefile.erb
For what I can see in #197, and particularly in [this commit](https://github.com/platanus/potassium/pull/197/commits/8749a9eaa54229d091238137178ad799e05754b7) the original idea was for the names to be what these PR indicates.
The idea behind this is that `services-down` should just stop the containers/volumes (so that it's the contrary to up), but doing `down --volumes` actually destroys volume data
> fix(Makefile): change stop and down services names

- lib/potassium/recipes/vue_admin.rb
- Found a case when using shorthand syntax for Vue binding keys, the translation throws an exception.
- For example: `v-bind:key` can be written as `:key` and this was causing an error.
>  fix(vue-admin): fix case when binding case uses shorthand syntax

- lib/potassium/assets/Makefile.erb
- lib/potassium/assets/bin/setup.erb
- lib/potassium/recipes/database_container.rb
- spec/features/database_container_spec.rb
- Removes simple `docker-compose` commands and `bin/setup` from Makefile
- Changes help to only include instructions for backup/restore
> Remove makefile commands

- CHANGELOG.md
With #279 Makefile commands were removed, overriding #273
> fix(changelog): update makefile entry

- lib/potassium/recipes/front_end.rb
Since we're moving to a mobile-first design system, this tag should be added automatically when setting up a new project.
> feat(frontend): add responsive meta tag during setup

- lib/potassium/recipes/ci.rb
Change `circleci` folder name to `.circleci` so that CircleCI integration works right out of the box.
> fix(ci): Change circleci folder name to .circleci

- lib/potassium/recipes/front_end.rb
- spec/features/front_end_spec.rb
Since webpacker is the default js compiler of Rails, new projects [already come with a `javascript_pack_tag` in the layout file](https://github.com/rails/rails/commit/4838c1716a0340137d858fab49bf460e23be5a4b#diff-eacee044d2d703bce71ec1447308e9beR13). 
This removes the manual insertion of the tag in the frontend recipe.
Fixes #295
> fix(front-end): remove manual insertion of js pack tag

- CHANGELOG.md
- lib/potassium/assets/app/uploaders/base_uploader.rb
- lib/potassium/assets/config/shrine.rb
- lib/potassium/recipes/file_storage.rb
- spec/features/file_storage_spec.rb
Fixes a couple of issues that arrise when using shrine as file storage:
- In the `Attacher.validate` block `allowed_type` was being accessed directly, but it wasn't available in that context. Now it is accessed through the `store` (instance of uploader)
- Define cache storage in test env
- Add path for saved files in dev env to `.gitignore`
> Shrine fixes

- lib/potassium/assets/.eslintrc.json
Add `"node": true` for the files outside of the folder `/app`.
- This avoids the raise of errors for methods like `require` or `model.export` that are used in most configurations files.
> feat(.eslintrc.json): add overrides rules for files outside of app/

- CHANGELOG.md
- README.md
- lib/potassium/cli/commands/create.rb
- lib/potassium/cli_options.rb
- lib/potassium/newest_version_ensurer.rb
- lib/potassium/node_version_ensurer.rb
This PR adds a version check for the node version. Node is a dependency for potassium and project creation often broke due to node incompatibilities. 
- The node version check is performed and communicated via exceptions. It can be disabled (at users own risk, for example to use a newer version of node) via the `--no-node-version-check` flag.
- The way the potassium version was checked is also modified to fit the new exception-based flow.
> Node version check

- potassium.gemspec
Addressing [this](https://github.com/platanus/potassium/network/alert/potassium.gemspec/rake/open)
> feat(dependencies): bump rake in development for security update

- CHANGELOG.md
- lib/potassium/assets/config/puma.rb
When puma is launching rails hasn't had the chance to overload the integers with the .day method
> fix(config/puma): replace rails .day method

- CHANGELOG.md
- lib/potassium/assets/testing/rails_helper.rb
Se apagan los observers en el ambiente de test
> feat(rails-helper): disable observers while testing

- CHANGELOG.md
- README.md
- lib/potassium/cli_options.rb
- lib/potassium/recipes/github.rb
- potassium.gemspec
- spec/features/github_spec.rb
- spec/spec_helper.rb
- spec/support/fake_octokit.rb
**Description**
This PR replaces the use of hub to create repositories with usage of the Github API using the Octokit gem.
The downside of this approach is that the user must enter a[ Personal Access Token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) to authenticate. An alternative would be to keep using hub, but if hub fails to use this as a second approach.
Closes #238
> GitHub octokit

- CHANGELOG.md
- lib/potassium/assets/redis.yml
- lib/potassium/recipes/background_processor.rb
- spec/features/background_processor_spec.rb
Adds the necessary configuration to docker-compose.yml and the corresponding env vars.
Also changes the `redis.yml` config file to force the definition of the `REDIS_URL` env var in development in an effort to make it more consistent with production.
closes #328
> feat(background_processor): include redis docker configuration

- lib/potassium/assets/README.yml
- lib/potassium/assets/app/graphql/graphql_controller.rb
- lib/potassium/assets/app/graphql/mutations/login_mutation.rb
- lib/potassium/assets/app/graphql/queries/base_query.rb
- lib/potassium/assets/app/graphql/types/base/base_argument.rb
- lib/potassium/assets/app/graphql/types/base/base_enum.rb
- lib/potassium/assets/app/graphql/types/base/base_field.rb
- lib/potassium/assets/app/graphql/types/base/base_input_object.rb
- lib/potassium/assets/app/graphql/types/base/base_interface.rb
- lib/potassium/assets/app/graphql/types/base/base_object.rb
- lib/potassium/assets/app/graphql/types/base/base_scalar.rb
- lib/potassium/assets/app/graphql/types/base/base_union.rb
- lib/potassium/assets/app/graphql/types/mutation_type.rb
- lib/potassium/assets/app/graphql/types/query_type.rb
- lib/potassium/assets/config/graphql_playground.rb
- lib/potassium/cli_options.rb
- lib/potassium/recipes/api.rb
- lib/potassium/recipes/front_end.rb
- spec/features/api_spec.rb
- spec/features/front_end_spec.rb
- spec/features/graphql_spec.rb
Se agrega la opción de tener una API GraphQL a la receta de api. Esto implica principalmente el uso de la gema [graphql](https://graphql-ruby.org/) y la generación de la estructura del proyecto gql en la carpeta `graphql`. Además se usa la gema [graphql-playground](https://github.com/papodaca/graphql_playground-rails) para generar la documentación automática con el ambiente de prueba de las consultas. También se incluye la instalación y configuración de [vue-apollo](https://apollo.vuejs.org/) para el frontend. Gran parte esta basado en lo que hizo @GabrielLyonB  en su repo de prueba para la presentación de hace un par de meses.
En teoría este PR es lo mínimo suficiente para generar una App Vue+backend-GraphQL-rails en la que se puede empezar a desarrollar inmediatamente.
La instalación …
> Feat/ Beta support for graphql

- .circleci/config.yml
- .gitignore
- .rubocop.yml
- lib/potassium/version.rb
- potassium.gemspec
- spec/support/potassium_test_helpers.rb
Previously in Platanus, we used Hound to lint our PRs. Lately we are using reviewdog in our new projects. This PR changes potassium itself to use reviewdog.
- Fixes an issue in test helpers where a test project would run `hound`, which would overwrite the 0.82 rules with th 0.65
- Changes rubocop version, adds needed dependencies and copies rules used for generated projects to potassium root
- Updates CI config:
- Uses v2.1 and recent syntax (executors, commands, etc)
- Doesn't set bundle path as it was throwing errors in tests. Instead, use default path and add that for cache
- Change parallelism to 6, it may not be much of an improvement but it's to check if it is
> Migrate to reviewdog

- .circleci/config.yml
I broke cache restore in #335 😅 . The problem was that path `/usr/local/bundle` couldn't be written to, so restore cache failed and the job stoped.
This PR fixes it by changing bundle path. I was trying to use `vendor/bundle` but it had 2 problems:
- It's a relative path, so when in the tests `bin/potassium` is run inside of `tmp` folder it wasn't finding it -> fixed by using absolute path
- Bundle path was changed, but ruby still wasn't finding the gems. I tried setting `GEM_HOME` [like it was before](https://github.com/platanus/potassium/blob/6a932c36d83ca522fe32ea61eccd2c6a4897e7cb/.circleci/config.yml#L11), but it didn't work, not sure why -> fixed by setting `GEM_PATH`
Also, cache key was changed to avoid hits with previous flawed cache.
In [the latest …
> fix(ci-config): change cache path

- CHANGELOG.md
- README.md
- lib/potassium/assets/README.yml
- lib/potassium/cli_options.rb
- spec/features/background_processor_spec.rb
In #137 delayed jobs was removed as a background processor option, and the recipe was changed to a yes/no question to include sidekiq
- Removes delayed jobs from used technologies section of potassium and generated projects readme
- Fixes the cli option, changing it to a switch
> Remove delayed jobs remnants

- CHANGELOG.md
- lib/potassium/recipes/heroku.rb
**Description**
Closes #331 
When the default app name or default pipeline name exceeds 30 characters (the limit set by Heroku), the user is prompted to input a new name. This name doesn't have to include either the name prefix or the environment name at the end (should we enforce that?).
Heroku app names are now set during the ask section of the recipe. This is because it doesn't make sense to ask a user for a Heroku app name if they don't want to deploy the app.
> Validate names in heroku recipe do not exceed the name limit

- CHANGELOG.md
- lib/potassium/version.rb
Release con las últimas cosas que tenemos en Unreleased:
Features:
- Add Google Tag Manager [#326](https://github.com/platanus/potassium/pull/326)
- Update rubocop and rubocop-rspec for potassium and generated projects [#337](https://github.com/platanus/potassium/pull/337)
- Adds `mailers` queue to `sidekiq.yml` when installing or creating mailer recipe [#341](https://github.com/platanus/potassium/pull/341)
Fixes:
- Change `backgroud_processor` cli option to a switch. As of [#137](https://github.com/platanus/potassium/pull/137) we no longer have `delayed_jobs` as an option, it's only `sidekiq` now [#340](https://github.com/platanus/potassium/pull/340)
- Fixes mailer recipe install when background_processor wasn't installed [#341](https://github.com/platanus/potassium/pull/341)
- Update …
> chore(): release v6.2.0

- CHANGELOG.md
- lib/potassium/recipes/front_end.rb
Jest v27 changed some defaults. The default test environment changed from `jsdom` to `node`. This breaks our current app spec.
More information in [this response](https://github.com/vuejs/vue-test-utils/issues/999#issuecomment-850273753)
> fix(recipes/front_end): add jsdom explicitly as test environment

- .circleci/config.yml
- .circleci/setup-rubygems.sh
- README.md
Implements the same [circleci deploy mechanism](https://github.com/platanus/parxer/blob/787e0d3e138ed33323362402d5ea5e896c2662f8/.circleci/config.yml#L73) as in [parxer](https://github.com/platanus/parxer)
> chore(circleci): publish to rubygems

- CHANGELOG.md
- lib/potassium/assets/app/javascript/app.spec.js
The `isVueInstance` method [is deprecated](https://vue-test-utils.vuejs.org/api/wrapper-array/isvueinstance.html) and triggers a warning.
The proposed way [tests exactly the same](https://github.com/vuejs/vue-test-utils/blob/2d6b49780c7e1d663b877ddf5d6492ed7b510379/packages/test-utils/src/wrapper.js#L400) but avoids the warning message.
> chore(assets/app/js/app.spec.js): remove deprecated method

- CHANGELOG.md
- lib/potassium/recipes/api.rb
Include `run_test!` to Rspec example groups for swagger API documentation/testing. 
This is mentioned in issue #362.
> feat(rubocop): add run_test! example group for swagger in rpsec

- CHANGELOG.md
- lib/potassium/version.rb
Features
- Updates ActiveAdmin installation to use webpacker [#350](https://github.com/platanus/potassium/pull/350)
- Replaces Active Skin with Arctic Admin [#350](https://github.com/platanus/potassium/pull/350)
Fixes
- Forces `vue-loader` version to 15, as 16 requires `@vue/compiler-sfc`, which is a part of Vue 3 [#375](https://github.com/platanus/potassium/pull/375)
- Changes Content Security Policy added by GTM recipe to: [#375](https://github.com/platanus/potassium/pull/375)
- Include the same config regardless of environment
- Include `unsafe_eval` in `script_src`, as it is required for Vue's compiler build
- Changes the front-end test to avoid using the deprecated method `isVueInstance` [#376](https://github.com/platanus/potassium/pull/376)
> Release 6.4.0

- CHANGELOG.md
- README.md
- lib/potassium/recipes/heroku.rb
- spec/features/heroku_spec.rb
In this PR the `rails_stdout_logging` is removed from the `heroku` recipe as it isn't needed anymore (since Rails 5) and it was generating a Deprecation Warning.
More info here:
[https://github.com/heroku/rails_stdout_logging#rails-5](https://github.com/heroku/rails_stdout_logging#rails-5)
> chore(): remove rails_stdout_logging gem

- lib/potassium/assets/.circleci/config.yml.erb
closes #381
I added the ability of clearing the cache with two different env vars, to differentiate between bundler cache and yarn cache.
To use this new feature to "clear" the cache, one can go to the env vars section in the projects settings tab in CircleCI and add/change the `BUNDLE_CACHE_VERSION` or the `YARN_CACHE_VERSION` env var with something like v1 or v2 and so on. If the var is new, the restore cache steps of the build won't find anything and it will proceed without a hit. Then, a new cache will be saved.
> feat(ci): add env var to cache key to allow clearing it

- lib/potassium/assets/.pryrc
With our potassium setup, there's a bug that causes activeadmin resources default actions (view/edit/delete) to not appear after using `binding.pry`. The only working solution when that happens is to restart the server.
I did a little digging, and found out that the bug was caused because of the piece of code that this PR removes:
The `include Rails::ConsoleMethods` was adding some methods, in particular `reload!`, to the pry session, probably because of [this notice in pry docs](https://github.com/pry/pry/wiki/Setting-up-Rails-or-Heroku-to-use-Pry#a-minor-fix-needed-on-rails-32). However, for `rails console`, that was [already being done by the gem `pry-rails`](https://github.com/rweng/pry-rails/blob/master/lib/pry-rails/railtie.rb#L25), so adding this code to the `.pryrc` was only …
> fix(pryrc): remove ConsoleMethods

- CHANGELOG.md
- lib/potassium/assets/README.yml
- lib/potassium/assets/active_admin/admin_user_policy.rb
- lib/potassium/assets/active_admin/comment_policy.rb
- lib/potassium/assets/active_admin/policies/admin_user_policy.rb
- lib/potassium/assets/active_admin/policies/comment_policy.rb
- lib/potassium/assets/active_admin/policies/default_policy.rb
- lib/potassium/assets/active_admin/policies/page_policy.rb
- lib/potassium/assets/active_admin/pundit_page_policy.rb
- lib/potassium/recipes/pundit.rb
- spec/features/pundit_spec.rb
Different pundit settings for app and Active Admin.
Active admin policies now go inside the `BackOffice` namespace.
Active admin policies now inherit from `BackOffice::DefaultPolicy`.
> Active Admin - Pundit

- CHANGELOG.md
- lib/potassium/version.rb
Webpacker 4 is incompatible with the "newly" released webpack-dev-server@4, which may be breaking new projects created with potassium.
Updating Rails to 6.1 gives us access to Webpacker 5 which fixes the problem by fixing the version of the package to 3.
Mostly a placeholder until Webpacker 6 gets released, with compatibility with wds@4.
---
For existing projects: Upgrading to Rails 6.1 and Webpacker 5 seems to be seamless with our current setup, none of the [changes](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-6-0-to-rails-6-1) should affect us but of course it depends on the project. Tested with mok and it worked as-is after running the update helper.
> chore(): update rails to 6.1

- CHANGELOG.md
- lib/potassium/recipes/api.rb
- Add `run_test!` as an example group in rubocop for swagger api.
- This was incorrectly implemented in this previous [PR](https://github.com/platanus/potassium/pull/379).
> feat(recepies/api): include 'run_test!' as an example group for swagger

- CHANGELOG.md
- lib/potassium/assets/Aptfile
- lib/potassium/assets/README.yml
- lib/potassium/assets/app/jobs/shrine_promote_job.rb
- lib/potassium/assets/app/serializers/base_serializer.rb
- lib/potassium/assets/app/serializers/concerns/image_handling_attributes.rb
- lib/potassium/assets/app/uploaders/cover_image_uploader.rb
- lib/potassium/assets/config/initializers/shrine/plugins/image_handling_utilities.rb
- lib/potassium/assets/config/shrine.rb
- lib/potassium/recipes/file_storage.rb
- spec/features/file_storage_spec.rb
This PR adds come things to facilitate image processing and handling in our projects, aimed at decreasing image loading times and improving loading experience. This is done mainly with the following elements:
-  Size derivatives: when uploading an image as an attachment of some model, we are generating three different sizes for that image. If we use an appropriate size for each part the image is used we could decrease the weigth of the payload the frontend has to render
- Webp derivatives: generally lower weight compared to a jpg or png alternative, without big quality sacrifice. They're not 100% supported by browsers, so jpg alternatives are also included
- [Blurhash](https://blurha.sh/): it's a string code generated from an image. The frontend decodes it and paints it in a `<canvas>` …
> Image handling

- lib/potassium/recipes/coverage.rb
- lib/potassium/recipes/front_end.rb
- spec/features/coverage_spec.rb
Potassium uses Jest for testing frontend code when using Vue. Jest provides some options to report test coverage. 
Change the `coverage` recipe to add the necessary setup for Jest test coverage (if Jest is used). It modifies the existing `package.json` to add the coverage configuration.
> feat(coverage-recipe): add front end coverage for jest

- CHANGELOG.md
- lib/potassium/assets/.rubocop.yml
- lib/potassium/recipes/style.rb
En Platanus es un desafío grande transmitir las decisiones que vamos tomando en relación a estándares y buenas prácticas de desarrollo. Por ej: si empezamos a usar jobs en vez de comandos, ¿cómo hacemos que este cambio se empiece a aplicar en todos los proyectos? o si está prohibido usar una gema x, ¿cómo le avisamos a la gente que use una alternativa?
Basado en esta [investigación](https://github.com/593f4e45720245a1b35a58a70592f9c2?p=e8d9b39c29b44366b835c84eacbc9c2f), descubrimos que es factible transmitir esta información usando reglas custom de Rubocop.
Ya se creó la gema [rubocop-platanus](https://github.com/platanus/rubocop-platanus) como una extension de rubocop con estas reglas custom.
Se agrega la gema rubocop-platanus y su configuración al recipe de nuevos proyectos.
> feat(recipe): add rubocop-platanus to recipe

- lib/potassium/recipes/file_storage.rb
Se mueven lineas para instalar vips antes del resto
> fix(file-storage): prepend vips installation

- lib/potassium/assets/.circleci/config.yml.erb
- lib/potassium/recipes/front_end.rb
Adds type checking to reviewdog.
> feat(circleci): add typescript check

- lib/potassium/assets/.circleci/config.yml.erb
tsc (and vue-tsc) need to be run without a list of files, otherwise it can't find project-defined types. ReviewDog has its own diff filter so it should post only relevant comments.
> fix(circleci): fix tsc check

- lib/potassium/assets/app/javascript/api/index.ts
- lib/potassium/assets/app/javascript/utils/case-converter.ts
- lib/potassium/recipes/front_end.rb
- spec/features/front_end_spec.rb
It is common that on a generated project one manually adds an `api` object that wraps `axios` and camelizes/decamelizes keys from requests/responses.
- Create two files that are copied into the generated project.
- `app/javascript/api/index.ts`: the `api` object
- `app/javascript/utils/decamelizer.ts`: an implementation of decamelize that doesn't delete the information of a `File` type object sent in requests.
- Added a `setup_api_client` method in the `front_end` recipe that installs `axios` and `humps` and copies the files into the generated project.
- Tests for the `setup_api_client` method
> feat(recipes/front_end): add initial api files

- CHANGELOG.md
- lib/potassium/assets/.circleci/config.yml.erb
Los proyectos generados recientemente con potassium tienen configurado para que monkeyci comente en los prs cuando alguno de los cambios introducidos en el pr no está testeado. Está pasando que el mono habitualmente se equivoca y comenta sobre líneas que si están testeadas, incluso en el mismo PR.
Se arregla este bug. El problema era que, el reporte de coverage que se generaba debido a los tests de sistema estaba sobreescribiendo al reporte de los unitarios. Es decir, reportaba cualquier cambio del pr que no estuviera cubierto por un test de sistema.
Para solucionarlo, simplemente se mueve el reporte de coverage de reviewdog para que ocurra después de los unitarios pero antes de los de sistema. Otra alternativa hubiera sido mergear ambos reportes, que está soportado por simplecov, pero en …
> fix(ci-config): run simplecov after unit and before system tests

- lib/potassium/assets/.eslintrc.json
- lib/potassium/assets/app/javascript/api/index.ts
- lib/potassium/assets/app/javascript/utils/case-converter.ts
- lib/potassium/recipes/front_end.rb
- lib/potassium/recipes/style.rb
- Agrega reglas override para evitar alertas que no son necesarias cuando se trabaja en archivos Vue con typescript
- Mueve todas las dependencies de NPM a un hash para que sea más fácil revisar y/o cambiar lo que se está instalando
- Agrega type a los datos procesados por `convertKeys`
> Frontend updates

- lib/potassium/assets/tsconfig.json
In order to use mocks in front end tests, it is necesary to exclude them in the  `tsconfig.json` file. 
The files ending in`.mock.ts` are excluded, so that when someone adds a mock file to the project the app keeps compiling. 
The `tsconfig.json` file
> fix(tsconfig): exclude mock files

- lib/potassium/assets/app/javascript/api/__mocks__/index.mock.ts
- lib/potassium/recipes/front_end.rb
- spec/features/front_end_spec.rb
In a previous PR we excluded `.mock` files from the `tsconfig.json` . Now we want to add a very simple example of a mock
A mock example file for the `api/index.ts` was added
- The example mok `index.mock.ts`
- The `frontend recipe` where this file was copied
> feat(mok-example/FrontEndRecipe): add mock example for api index

- lib/potassium/assets/config/sentry.rb.erb
- lib/potassium/recipes/error_reporting.rb
- spec/features/error_reporting_spec.rb
We are using` sentry-raven`  which is deprecated, so we want to upgrade to `sentry-rails` 💎 
​
The upgrade to `sentry-rails `according to the guide linked below.
​
The initializer `sentry.rb`.
​
-----------
- raven `sanitize_fields` is removed  from `sentry-ruby`
- sentry-ruby doesn't capture raven_context from exceptions anymore. 
https://docs.sentry.io/platforms/ruby/migration/
Builder card: https://www.notion.so/platanus/Upgrade-de-sentry-raven-a-sentry-rails-a946a8fa22974bafaa372ac716668f5c
> feat(sentry): replace sentry raven with sentry rails

- CHANGELOG.md
- lib/potassium/templates/application.rb
Se saca enumerize, de hace rato se usan los enums built in en Rails
> feat(application-template): remove enumerize

- CHANGELOG.md
- lib/potassium/assets/.rubocop.yml
Se habilitan algunas reglas nuevas en rubocop:
- [Rails/Delegate](https://docs.rubocop.org/rubocop-rails/2.17/cops_rails.html#railsdelegate)
- [Rails/I18nLocaleAssignment](https://docs.rubocop.org/rubocop-rails/2.17/cops_rails.html#railsi18nlocaleassignment)
- [Rails/WhereEquals](https://docs.rubocop.org/rubocop-rails/2.17/cops_rails.html#railswhereequals)
- [Rails/WhereNot](https://docs.rubocop.org/rubocop-rails/2.17/cops_rails.html#railswherenot)
- [Rails/RedundantPresenceValidationOnBelongsTo](https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsredundantpresencevalidationonbelongsto)
- [Layout/ClassStructure](https://docs.rubocop.org/rubocop/1.24/cops_layout.html#layoutclassstructure)
Esta última me gustaría que se revise particularmente. Se define un orden en el que van los …
> feat(assets-rubocop-yml): enable new rules

- lib/potassium/recipes/vue_admin.rb
En un Ethical Hacking se encontró que nuestra forma de usar Vue en el admin es vulnerable a ataques de Client-Side Template Injection. Por ejemplo si un usuario escribe `{{ 13 + 13 }}`, en el admin en las vistas de Index y Show se va a ver como `26`. Esto puede ser cualquier tipo de javascript (detalles: https://book.hacktricks.xyz/pentesting-web/client-side-template-injection-csti#vuejs )
Este fix comenta el mount de Vue para que sea una decisión explícita el montar Vue en un elemento.
> feat(vue-admin): comment out the vue mount point

- lib/potassium/assets/.circleci/config.yml.erb
- lib/potassium/assets/config/initializers/session_store.rb
- lib/potassium/recipes/background_processor.rb
- lib/potassium/recipes/redis.rb
- lib/potassium/templates/application.rb
- spec/features/redis_spec.rb
En un Ethical Hacking se encontró la siguiente vulnerabilidad:
> Se detecta que la cookie de sesión de usuario no expira cuando el usuario conectado cierra la sesión. Es posible utilizar la misma cookie en un request en otro navegador y volver a iniciar sesión, sin necesidad de entregar credenciales de autenticación.
Devise se lava las manos (https://github.com/heartcombo/devise/issues/5348) y apunta a la documentación de Rails (https://guides.rubyonrails.org/security.html#replay-attacks-for-cookiestore-sessions) que dice que la mejor solución es no usar CookieStore para guardar sesiones.
Este PR reemplaza CookieStore con Redis. Así, Devise puede borrar la sesión en el store e invalidar la cookie sin importar si alguien la ha copiado o no.
Hay otras alternativas pero todas son medias …
> Redis session

- lib/potassium/recipes/admin.rb
En un Ethical Hacking se encontró que los comentarios de Active Admin no sanitizan el HTML ingresado, lo que permitiría guardar y mostrar cualquier tipo de contenido. El alcance de esta vulnerabilidad es super limitado (solo afectaría a admins) pero de todas maneras, como en general no usamos los comments, mejor partir con ellos desactivados.
> feat(admin): disable comments

- lib/potassium/recipes/mailer.rb
- spec/features/environment_variables_spec.rb
- spec/features/mailer_spec.rb
- Fix a un test que faltaba el setup del proyecto dummy [que está en los demás tests](https://github.com/platanus/potassium/blob/master/spec/features/file_storage_spec.rb#L5). Falla solo cuando este es el primer test que se corre, ya que en otros casos ya habría una db y proyecto creados
- Fix a una linea de mailer que se agregaba que tenía un error de linter que se fixeaba y fallaba el test por eso
> Fixes failing tests

- lib/potassium/assets/.eslintrc.json
- lib/potassium/assets/tsconfig.config.json
- lib/potassium/assets/tsconfig.json
- lib/potassium/recipes/front_end_vite.rb
Se arreglan un par de cosas relacionadas a ts y vitest:
- Se hacen cambios en la tsconfig relacionados a vue [para soportar TS v5](https://github.com/vuejs/tsconfig#migrating-from-typescript--50)
- Se agrega vite/client [para soportar importación de assets](https://vitejs.dev/guide/features.html#client-types) (como svgs) 
- [Se mueven los globals de vitest al lugar correcto](https://vitest.dev/config/#globals)
> fix(): fix tsconfig vite and vitest config

- CHANGELOG.md
- lib/potassium/recipes/testing.rb
- spec/features/testing_spec.rb
En un par de proyectos más antiguos, guard estaba tomando mucho tiempo (un par de decenas de segundos en vez de un par de segundos en otros proyectos. Este PR agrega un ignore al Guardfile, que le dice a guard [ignore ciertos directorios](https://github.com/guard/guard/wiki/Guardfile-DSL---Configuring-Guard#ignore), en particular node_modules que no viene ignorado por defecto, y otros. En los proyectos que tenían este problema, esta configuración normalizó los tiempos
> perf(testing): ignore irrelevant folders in guard

- CHANGELOG.md
- lib/potassium/recipes/i18n.rb
- spec/features/i18n_spec.rb
Potassium agrega i18n y `es-CL` o `en` como idioma por defecto. También agrega un par de fallbacks.
Este PR saca una configuración que se agregaba por defecto en `production.rb`, `config.i18n.fallbacks = true`. Potassium ya configura los callbacks en el `application.rb` con otro valor, entonces estaba pasando que la configuración en producción y local eran diferentes.
En la mayoría de los casos no es mucho problema, ya que en ambos toma el idioma seleccionado, `es-CL`. Pero en caso de no tener una traducción, en local pasaba a los fallbacks `es` y `en`, mientras que en producción tiraba un error de translation missing
> feat(i18n): remove i18n fallback config in prod
